name: Docker Build new

on:
   workflow_dispatch:
   
env:
  CONTAINER_REGISTRY: docker.io
  CONTAINER_IMAGE: samplerak
  REPOSITORY_NAME: sharon111edapal
  IMAGE_TAG: ${{ github.run_number }}
  AWS_REGION: ap-south-1
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Login to Git Hub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ env.REPOSITORY_NAME }}
          password: ${{ secrets.RAK }}

      - name: Build and push Docker image - Dynamic
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.REPOSITORY_NAME }}/${{ env.CONTAINER_IMAGE }}:${{ env.IMAGE_TAG }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        
      - name: Deploy
        run: |
          aws eks update-kubeconfig --name rak-eks-cluster
          sed -i "s/latest/${{ env.IMAGE_TAG }}/" deployment.yaml
          kubectl apply -f deployment.yaml
